#!/usr/bin/env bash

# Automatically set up irssi for autoconnect and notifications

# Author: Christopher Markieta

set -e

# Terminator 
# if ! screen -list | grep -q 'irssi'; then screen -smS irssi irssi; else screen -x irssi; fi
